Changes to make adding to home screen better
MelroseSTLs/AspenAppWebframe pull request #12
Opened 2017-06-07 20:43 UTC by Veldrovive

I added icons that will appear on the home screen (Not final, I'm no graphic designer so by all means change it). I also added a script that prompts the user to add the site to their home screen.

2017-06-07 22:27 UTC, Veldrovive commented
Don't tell me to fix the codacy issues. It's someone else's code and I don't want to break it by changing stuff.

2017-06-09 14:08 UTC, HeroCC commented
Icons are fine, but I don't like the huge js / CSS homescreen library. Instead, use something like this for a native integration: https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

2017-06-09 15:07 UTC, HeroCC requested changes
Separate your PRs and make the icons transparent. Otherwise, thanks!

2017-06-09 15:07 UTC, HeroCC commented on index.html
> +  <link rel="apple-touch-icon" sizes="57x57" href="./img/ios-icon-57x57.png" />
These icons should have transparent backgrounds, not white. And, don't include the '.' in the path

2017-06-09 15:07 UTC, HeroCC commented on index.html
> +  <script src="./js/addtohomescreen.min.js"></script>
We don't really need this, chrome supports it nativity and it adds a lot of bloat / code to maintain

2017-06-09 15:07 UTC, HeroCC commented on index.html
> +      addToHomescreen();
Use as little script tags in HTML as possible, include this in main.js if we end up using it?

2017-06-09 15:27 UTC, HeroCC commented on index.html
> +  <link rel="apple-touch-icon" sizes="57x57" href="./img/ios-icon-57x57.png" />
And when previewing the SVG, it appears blank? Just a transparent image? Is that just me or did you upload the wrong thing?

2017-06-09 18:06 UTC, Veldrovive commented on index.html
> +  <link rel="apple-touch-icon" sizes="57x57" href="./img/ios-icon-57x57.png" />
IOS has non transparent backgrounds so I made them non transparent. The SVG isn't blank, it seems like GitHub is simply not displaying it correctly.

2017-06-11 16:59 UTC, HeroCC commented
I made a baseline for schedule push notifications, so the manifest stuff was superseded, can you make it just the icons?

2017-09-14 19:27 UTC, closed without merging