Same tweaks as before with a bit extra
MelroseSTLs/AspenAppWebframe pull request #2
Opened 2017-05-30 22:16 UTC by Veldrovive

With the fear of sounding unprofessional, don't commit a bunch of stuff and create a ton of conflicts this time, ok?

I changed it so that it will wait for school hours to come before starting the program and then I just made it so it uses time to generate the percentage instead of block.
Also I do have the gitignore there so that it doesn't take the .idea folder.

2017-05-30 23:42 UTC, HeroCC requested changes
Small stuff this time 😉

2017-05-30 23:42 UTC, HeroCC commented on js/main.js
> +  return date.getHours()*(60*60*1000) + date.getMinutes()*(60* 1000) + date.getSeconds()*(1000) + date.getMilliseconds();
What units does this return in? Seconds? Ms? Make the function name more descriptive

2017-05-30 23:42 UTC, HeroCC commented on js/main.js
> +  var time = +countDownDate;
Eww

2017-05-30 23:42 UTC, HeroCC commented on js/main.js
> +    var today = new Date();
This is already defined in this scope (Line 1)

2017-05-31 00:32 UTC, Veldrovive commented on js/main.js
> +  var time = +countDownDate;
Yea. This is actually correct. We were right that += is correct, but +date actually is a typecast. This is saying turn countDownDate into milliseconds.

2017-05-31 12:17 UTC, HeroCC commented
Looks good! Now make codacy happy, for some reason GitHub won't let me merge if the CI is failing.

2017-05-31 12:53 UTC, Veldrovive commented
I can't. I could pull out some of the clock function to reduce the complexity, but I want to completely restart the program by running the main function which will always result in reciprocal calling of function. What I will do for now is just force a reload of the page to run the main function that way.

2017-05-31 13:22 UTC, merged

2017-05-31 13:22 UTC, HeroCC commented
Not gods approve, thanks!